### PR TITLE
Pin `fsspec==2022.5.0`

### PR DESCRIPTION
**Pull request by karlhigley**
`fsspec 2022.7.0` breaks `Dataset.to_parquet`, so pinning to an earlier version to avoid that

### CODE REVIEW

**Review by nv-alaiacano — APPROVED** [review]

**Comment by karlhigley** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Comment by karlhigley** [comment]
rerun tests

**Pull request merged**
