### PR TITLE
Fix Graph.remove_inputs

### PR DESCRIPTION
**Pull request by benfred**
The `remove_inputs` call on the graph wasn't working - since it was hanging on
to a reference to the removed columns via the `dependencies` list. Fix and
add a unittest that would have caught this.

Fixes https://github.com/NVIDIA-Merlin/NVTabular/issues/1632

### CODE REVIEW

**Comment by nv-alaiacano** [comment]
It seems like we were all working on this at the same time. Either PR is fine by me. https://github.com/NVIDIA-Merlin/core/pull/107

**Review by karlhigley — APPROVED** [review]

**Comment by karlhigley** [comment]
I'm just noticing this PR after merging the other one, so...why not both? 😆

**Comment by nv-alaiacano** [comment]
Closing this because #107 was merged and we don't want to merge both!

**Comment by karlhigley** [comment]
I actually don't think it's problematic to merge both here, so long as the tests pass. There may be subsequent clean-up we want to do, but this fix is really nice.

**Pull request closed without merging**
